class CodigoApp {
    API_ERROR = -1;
    LOGIN_OK = 0;
    INFORMACION_INCOMPLETA = 1;
    CORREO_NO_ENCONTRADO = 2;
    CORREO_NO_VALIDADO = 3;
    USUARIO_SIN_ROL = 4;
    USUARIO_SIN_CONFIGURACIONES = 5;
    PASSWORD_INCORRECTA = 6;

    NOMBRE_USUARIO_REGISTRADO = 7;
    CORREO_REGISTRADO = 8;
    CONFIGURACION_DEFAULT_INEXISTENTE = 9;
    REGISTRO_OK = 10;

    CUENTA_YA_VALIDADA = 11;
    CODIGO_DISTITO = 12;
    VALIDACION_OK = 13;

    CODIGO_REENVIADO_OK = 14;

    USUARIO_NO_REGISTRADO = 15;
}

module.exports = {
    CodigoApp
}